# Generated by Django 6.0.3 on 2026-03-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='release_date',
            new_name='date',
        ),
    ]
