# Generated by Django 6.0.3 on 2026-03-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_game_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ECO',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.TextField(blank=True),
        ),
    ]
